In [ ]:
a = [3,4,5]
b = a   ## That's called copy by reference 
b.append(6)
print(b) 
print(a)

[3, 4, 5, 6]
[3, 4, 5, 6]


In [ ]:
b = a.copy() ## copy by value
b.append(6)
print(b) 
print(a)


[3, 4, 5, 6, 6]
[3, 4, 5, 6]


In [ ]:
import copy
a = [3, 4, 5, [4]]
b = copy.deepcopy(a)  ## for being able to use [copy.] we imported copy 
b[-1].append(6)
print(b) 
print(a)


[3, 4, 5, [4, 6]]
[3, 4, 5, [4]]


### OOP by Python

### numpy 

In python 1D array means a list, by using numpy we can convert any list into an array. we gonna import numpy so that we won't have to use [numpy.] again & again rather we'll use [np.] 
If the shape of the array is like: (n,) where n = size; it's 1D array. 
If the shape of the array is like: (x,y) then it's a 2D array; 
where x = how many 1D lists or 1D arrays are in there {ROW}, y = how many elements are inside the 1D arrays or lists {COLUMN}.

In [ ]:
import numpy as np
arr = [1, 2, 3]
arr = np.array(arr) ## Now the list has become an array 
print(arr.shape)   
##print(arr.size)

(3,)


In [22]:
## 2D array

arr = [[2, 3, 4], 
       [1, 3, 5]]
arr = np.array(arr)
print(arr.shape)
print(arr[0,0])  ## It can be written as arr[0][0] too.
print(arr[0])    ## Row only 
print(arr)

(2, 3)
2
[2 3 4]
[[2 3 4]
 [1 3 5]]


In [15]:
x = np.random.random((3,3))
print(x)
y = np.random.randint(0, 50,(4,5))
print (y)

[[0.86345742 0.39957839 0.81358749]
 [0.05850842 0.09848572 0.23801013]
 [0.2963319  0.75718425 0.50032003]]
[[31 36 14 20 19]
 [ 4 44 39 28  2]
 [27 18 38 43 31]
 [28 27 19  9 24]]


In [18]:
z = np.zeros((4,5))
print(z)
n = np.ones((4,5))
print(n)
f = np.full((4,5),7)
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [24]:
d = np.eye(3) ## since identity matrix is a square matrix (3) means (3,3) / (3x3)
print(d)
d1 = (d+3)*100
print(d1)

 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[400. 300. 300.]
 [300. 400. 300.]
 [300. 300. 400.]]


In [29]:
## Slicing
a = np.array([
              [1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 0, 1, 2]
              ])

print(a[0:2, 2:])

[[3 4]
 [7 8]]


In [30]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)
print(x - y)
print(np.add(x, y)) # it works faster

print(x + 100)
print((x + 100) / 2)
print(np.dot(x,y))
print()

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 6  8]
 [10 12]]
[[101 102]
 [103 104]]
[[50.5 51. ]
 [51.5 52. ]]
[[19 22]
 [43 50]]



By using toList() we can convert an array into a list.

In [ ]:
## Reshape


In [32]:
import numpy as np
import matplotlib.pyplot as plt
import math